[[runners]]
  [runners.cache]
    Type = "${cache_type}"
    [runners.cache.gcs]
      BucketName = "${cache_bucket}"
  [runners.kubernetes]
    image = "ubuntu:18.04"
    ephemeral_storage_limit = "5Gi"
